AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Budget Alert Stack Set with SNS Notification'
 
Resources:
  Budget:
    Type: 'AWS::Budgets::Budget'
    Properties:
      Budget:
        BudgetName: 'MonthlyBudget'
        BudgetLimit:
          Amount: 50
          Unit: 'USD'
        TimeUnit: 'MONTHLY'
        BudgetType: 'COST'
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: 'ACTUAL'
            ComparisonOperator: 'GREATER_THAN'
            Threshold: 100
            ThresholdType: 'PERCENTAGE'
          Subscribers:
            - SubscriptionType: 'SNS'
              Address: !Ref SNSTopic
        - Notification:
            NotificationType: 'ACTUAL'
            ComparisonOperator: 'GREATER_THAN'
            Threshold: 50
            ThresholdType: 'PERCENTAGE'
          Subscribers:
            - SubscriptionType: 'SNS'
              Address: !Ref SNSTopic
        - Notification:
            NotificationType: 'ACTUAL'
            ComparisonOperator: 'GREATER_THAN'
            Threshold: 200
            ThresholdType: 'PERCENTAGE'
          Subscribers:
            - SubscriptionType: 'SNS'
              Address: !Ref SNSTopic
        - Notification:
            NotificationType: 'ACTUAL'
            ComparisonOperator: 'GREATER_THAN'
            Threshold: 300
            ThresholdType: 'PERCENTAGE'
          Subscribers:
            - SubscriptionType: 'SNS'
              Address: !Ref SNSTopic
 
  SNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: 'BudgetAlertsTopic'
      KmsMasterKeyId: 'alias/aws/sns' # Using the default AWS-managed KMS key for SNS encryption
      Subscription:
        - Protocol: 'email'
          Endpoint: 'myemail@mydomain.com'

  SNSTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      Topics:
        - !Ref SNSTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'budgets.amazonaws.com'
            Action: 'sns:Publish'
            Resource: !Ref SNSTopic
 
Outputs:
  BudgetName:
    Description: 'The name of the created budget'
    Value: !Ref Budget
  SNSTopicARN:
    Description: 'The ARN of the SNS topic'
    Value: !Ref SNSTopic
